project_id = "rxlpulfotwjizohyfulc"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.cyber-news-llm]
verify_jwt = false

[functions.multi-agent-blog-generator]
verify_jwt = false

[functions.blog-image-generator]
verify_jwt = false

[functions.generate-policy]
verify_jwt = false
