// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxlpulfotwjizohyfulc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4bHB1bGZvdHdqaXpvaHlmdWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2ODI5MDcsImV4cCI6MjA2MDI1ODkwN30.wt105oRs_0SOZznIh7l1_rMb9uwF-pI7jO5iEUd07D8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);